### ISSUE TITLE
Transaction with security=1 are created incorrectly

### ISSUE THREAD

**Issue by DaMarkov** [runplay/run-wallet-android#5]
I have send 100 IOTA from my security 1 address to someone else.
Here is the bundle hash:
K9RIGFNZRKOHFPSAEBCDIOIDOHCKBFGBTKBRCLTEKDXTTCGEBAQLYYPJHKSQCJEBKZVWLKXGVK9TARVW9

The bundle contains 4 transactions, but should only contain 3 since the address which was used to spent the IOTA is a security 1 address.
This results in the bundle never being confirmed by the network.
Additionally, when trying to reattach I get the error message "invalid hash error search".

The app has now published information about my private keys on the tangle without spending the IOTA from the associated addresses! Please fix.

**Comment by runplay** [comment]
Thanks, will look into it and fix

**Comment by runplay** [comment]
Still looking into this, the problem 99% sure lies in the jota api libarary from IF.

have raised #99
https://github.com/iotaledger/iota.lib.java/issues/99
but this does not fix this issue yet.

Until it is fixed, I am removing the solo Address change security option from run IOTA wallet, it will come back once I have solved it.

As a side note, I think the total iota trapped is 1.7ki ish, send me an Address, security 2 and I will get you that IOTA back, as its trapped until solved or works in another wallet, due to it being in the jota library I can see that all current IOTA wallets will have this problem, Trinity should not as I think that comes from the .js library.
iota@runplay.com best place to send the address

**Comment by runplay** [comment]
Have fixed this now, and is in v1.3.8400

**Comment by DaMarkov** [comment]
Thanks a lot!!
